module LaTeXSymbol where

(-->) :: a -> b -> (a,b)
(-->) = (,)

greek :: [(String, String)]
greek =
  [ "Alpha" --> "α"
  , "Beta" --> "β"
  , "Gammma" --> "Γ"
  , "Delta" --> "Δ"
  , "Epsilon" --> "Ε"
  , "Zeta" --> "Ζ"
  , "Eta" --> "Η"
  , "Theta" --> "Θ"
  , "Iota" --> "Ι"
  , "Kappa" --> "Κ"
  , "Lambda" --> "Λ"
  , "Mu" --> "Μ"
  , "Nu" --> "Ν"
  , "Xi" --> "Ξ"
  , "Omicron" --> "Ο"
  , "Pi" --> "Π"
  , "Rho" --> "Ρ"
  , "Sigma" --> "Σ"
  , "Tau" --> "Τ"
  , "Upsilon" --> "Υ"
  , "Phi" --> "Φ"
  , "Chi" --> "Χ"
  , "Psi" --> "Ψ"
  , "Omega" --> "Ω"
  
  , "alpha" --> "α"
  , "beta" --> "β"
  , "gamma" --> "γ"
  , "delta" --> "δ"
  , "epsilon" --> "ε"
  , "zeta" --> "ζ"
  , "eta" --> "η"
  , "theta" --> "θ"
  , "iota" --> "ι"
  , "kappa" --> "κ"
  , "lambda" --> "λ"
  , "mu" --> "μ"
  , "nu" --> "ν"
  , "xi" --> "ξ"
  , "omicron" --> "ο"
  , "pi" --> "π"
  , "rho" --> "ρ"
  , "sigma" --> "σ"
  , "tau" --> "τ"
  , "upsilon" --> "υ"
  , "phi" --> "ϕ"
  , "chi" --> "χ"
  , "psi" --> "ψ"
  , "omega" --> "ω"
  ]

greekMisc :: [(String, String)]
greekMisc =
  [ "vartheta" --> "ϑ"
  , "varpi" --> "ϖ"
  , "varrho" --> "ϱ"
  , "varsigma" --> "ς"

  , "Digamma" --> "Ϝ"
  , "digamma" --> "ϝ"
  ]

unaryOperator :: [(String, String)]
unaryOperator =
  [ "neg" --> "¬"
  ]

relationOperator :: [(String, String)]
relationOperator =
  [ "leq" --> "≤"
  , "leqq" --> "≦"
  , "leqslant" --> "⩽"
  , "lesssim" --> "≲"
  , "lessapprox" --> "⪅"
  , "prec" --> "≺"
  , "preceq" --> "≼"
  , "precsim" --> "≾"

  , "geq" --> "≥"
  , "geqq" --> "≧"
  , "geqslant" --> "⩾"
  , "gtrsim" --> "≳"
  , "gtrapprox" --> "⪆"
  , "succ" --> "≻"
  , "succeq" --> "≽"
  , "succsim" --> "≿"

  , "nless" --> "≮"
  , "nleq" --> "≰"
  , "lneq" --> "⪇"
  , "lneqq" --> "≨"
  , "lnsim" --> "⋦"
  , "lnapprox" --> "⪉"
  , "nprec" --> "⊀"
  , "npreceq" --> "⋠"
  -- no nleqslant

  , "ngtr" --> "≯"
  , "ngeq" --> "≱"
  , "gneq" --> "⪈"
  , "gneqq" --> "≩"
  , "gnsim" --> "⋧"
  , "gnapprox" --> "⪊"
  , "nsucc" --> "⊁"
  , "nsucceq" --> "⋡"
  -- no ngeqslant
  
  , "ll" --> "≪"
  , "lll" --> "⋘"

  , "gg" --> "≫"
  , "ggg" --> "⋙"
  
  , "lessgtr" --> "≶"
  , "lesseqgtr" --> "⋚"

  , "subset" --> "⊂"
  , "subseteq" --> "⊆"
  , "sqsubset" --> "⊏"
  , "sqsubseteq" --> "⊑"
  
  , "nsubset" --> "⊄"
  , "nsubseteq" --> "⊈"
  , "subsetneq" --> "⊊"
  
  , "supset" --> "⊃"
  , "supseteq" --> "⊇"
  , "sqsupset" --> "⊐"
  , "sqsupseteq" --> "⊒"
  
  , "nsupset" --> "⊅"
  , "nsupseteq" --> "⊉"
  , "supsetneq" --> "⊋"

  , "doteq" --> "≐"
  , "equiv" --> "≡"
  , "approx" --> "≈"
  , "cong" --> "≅"
  , "simeq" --> "≃"
  , "sim" --> "∼"
  , "propto" --> "∝"
  
  , "neq" --> "≠"
  , "nequiv" --> "≢"
  , "napprox" --> "≉"
  , "ncong" --> "≇"
  , "nsimeq" --> "≄"
  , "nsim" --> "≁"
  ]

arrows :: [(String, String)]
arrows =
  [ "to" --> "→"
  , "rightarrow" --> "→"
  , "Rightarrow" --> "⇒"
  , "longrightarrow" --> "⟶"
  
  , "gets" --> "←"
  , "leftarrow" --> "←"
  , "Leftarrow" --> "⇐"
  , "longleftarrow" --> "⟵"
  
  , "mapsto" --> "↦"
  , "longmapsto" --> "⟼"

  , "uparrow" --> "↑"
  , "downaroow" --> "↓"
  , "updownarrow" --> "↕"
  
  , "Uparrow" --> "⇑"
  , "Downarrow" --> "⇓"
  , "Updownarrow" --> "⇕"
  ]

misc :: [(String, String)]
misc =
  [ "partial" --> "∂"
  , "nabla" --> "∇"
  , "imath" --> "ı"
  , "jmath" --> "ȷ"
  , "ell" --> "ℓ"
  , "Re" --> "ℜ"
  , "Im" --> "ℑ"
  , "infty" --> "∞"
  , "wp" --> "℘"
  , "hbar" --> "ℏ"
  , "hslash" --> "ℏ"
  ]

hebrew :: [(String, String)]
hebrew =
  [ "aleph" --> "ℵ"
  , "beth" --> "ℶ"
  , "gimel" --> "ℷ"
  ]

blackboardBold :: [(String, String)]
blackboardBold =
  [ "bA" --> "𝔸"
  , "bB" --> "𝔹"
  , "bC" --> "ℂ"
  , "bD" --> "𝔻"
  , "bE" --> "𝔼"
  , "bF" --> "𝔽"
  , "bG" --> "𝔾"
  , "bH" --> "ℍ"
  , "bI" --> "𝕀"
  , "bJ" --> "𝕁"
  , "bK" --> "𝕂"
  , "bL" --> "𝕃"
  , "bM" --> "𝕄"
  , "bN" --> "ℕ"
  , "bO" --> "𝕆"
  , "bP" --> "ℙ"
  , "bQ" --> "ℚ"
  , "bR" --> "ℝ"
  , "bS" --> "𝕊"
  , "bT" --> "𝕋"
  , "bU" --> "𝕌"
  , "bV" --> "𝕍"
  , "bW" --> "𝕎"
  , "bX" --> "𝕏"
  , "bY" --> "𝕐"
  , "bZ" --> "ℤ"

  , "ba" --> "𝕒"
  , "bb" --> "𝕓"
  , "bc" --> "𝕔"
  , "bd" --> "𝕕"
  , "be" --> "𝕖"
  , "bf" --> "𝕗"
  , "bg" --> "𝕘"
  , "bh" --> "𝕙"
  , "bi" --> "𝕚"
  , "bj" --> "𝕛"
  , "bk" --> "𝕜"
  , "bl" --> "𝕝"
  , "bm" --> "𝕞"
  , "bn" --> "𝕟"
  , "bo" --> "𝕠"
  , "bp" --> "𝕡"
  , "bq" --> "𝕢"
  , "br" --> "𝕣"
  , "bs" --> "𝕤"
  , "bt" --> "𝕥"
  , "bu" --> "𝕦"
  , "bv" --> "𝕧"
  , "bw" --> "𝕨"
  , "bx" --> "𝕩"
  , "by" --> "𝕪"
  , "bz" --> "𝕫"
  
  , "bGG" --> "ℾ"
  , "bGP" --> "ℿ"
  , "bGS" --> "⅀"
  , "bGg" --> "ℽ"
  , "bGp" --> "ℼ"
  ]

blackboardBoldDigit :: [(String, String)]
blackboardBoldDigit =
  [ "b0" --> "𝟘"
  , "b1" --> "𝟙"
  , "b2" --> "𝟚"
  , "b3" --> "𝟛"
  , "b4" --> "𝟜"
  , "b5" --> "𝟝"
  , "b6" --> "𝟞"
  , "b7" --> "𝟟"
  , "b8" --> "𝟠"
  , "b9" --> "𝟡"
  ]
 
mathBoldDigit :: [(String, String)]
mathBoldDigit =
  [ "B0" --> "𝟎"
  , "B1" --> "𝟏"
  , "B2" --> "𝟐"
  , "B3" --> "𝟑"
  , "B4" --> "𝟒"
  , "B5" --> "𝟓"
  , "B6" --> "𝟔"
  , "B7" --> "𝟕"
  , "B8" --> "𝟖"
  , "B9" --> "𝟗"
  ]

parentheses :: [(String, String)]
parentheses =
  [ "[[" --> "⟦"
  , "]]" --> "⟧"
  , "<"  --> "⟨"
  , ">"  --> "⟩"
  , "<<" --> "⟪"
  , ">>" --> "⟫"
  , "{{" --> "⦃"
  , "}}" --> "⦄"
  , "(|" --> "⦇"
  , "|)" --> "⦈"
  , "((" --> "⦅"
  , "))" --> "⦆"
  
  , "(b" --> "⟅"
  , ")b" --> "⟆"
  , "lbag" --> "⟅"
  , "rbag" --> "⟆"
  ]
  
mathematicalCharacters :: [(String, String)]
mathematicalCharacters =
  [ "MiA" --> "𝐴"
  , "MiB" --> "𝐵"
  , "MiC" --> "𝐶"
  , "MiD" --> "𝐷"
  , "MiE" --> "𝐸"
  , "MiF" --> "𝐹"
  , "MiG" --> "𝐺"
  , "MiH" --> "𝐻"
  , "MiI" --> "𝐼"
  , "MiJ" --> "𝐽"
  , "MiK" --> "𝐾"
  , "MiL" --> "𝐿"
  , "MiM" --> "𝑀"
  , "MiN" --> "𝑁"
  , "MiO" --> "𝑂"
  , "MiP" --> "𝑃"
  , "MiQ" --> "𝑄"
  , "MiR" --> "𝑅"
  , "MiS" --> "𝑆"
  , "MiT" --> "𝑇"
  , "MiU" --> "𝑈"
  , "MiV" --> "𝑉"
  , "MiW" --> "𝑊"
  , "MiX" --> "𝑋"
  
  , "MiY" --> "𝑌"
  , "MiZ" --> "𝑍"
  , "Mia" --> "𝑎"
  , "Mib" --> "𝑏"
  , "Mic" --> "𝑐"
  , "Mid" --> "𝑑"
  , "Mie" --> "𝑒"
  , "Mif" --> "𝑓"
  , "Mig" --> "𝑔"
  , "Mih" --> "ℎ"
  , "Mii" --> "𝑖"
  , "Mij" --> "𝑗"
  , "Mik" --> "𝑘"
  , "Mil" --> "𝑙"
  , "Mim" --> "𝑚"
  , "Min" --> "𝑛"
  , "Mio" --> "𝑜"
  , "Mip" --> "𝑝"
  , "Miq" --> "𝑞"
  , "Mir" --> "𝑟"
  , "Mis" --> "𝑠"
  , "Mit" --> "𝑡"
  , "Miu" --> "𝑢"
  , "Miv" --> "𝑣"
  , "Miw" --> "𝑤"
  , "Mix" --> "𝑥"
  , "Miy" --> "𝑦"
  , "Miz" --> "𝑧"
   
  , "MIA" --> "𝑨"
  , "MIB" --> "𝑩"
  , "MIC" --> "𝑪"
  , "MID" --> "𝑫"
  , "MIE" --> "𝑬"
  , "MIF" --> "𝑭"
  , "MIG" --> "𝑮"
  , "MIH" --> "𝑯"
  , "MII" --> "𝑰"
  , "MIJ" --> "𝑱"
  , "MIK" --> "𝑲"
  , "MIL" --> "𝑳"
  , "MIM" --> "𝑴"
  , "MIN" --> "𝑵"
  , "MIO" --> "𝑶"
  , "MIP" --> "𝑷"
  , "MIQ" --> "𝑸"
  , "MIR" --> "𝑹"
  , "MIS" --> "𝑺"
  , "MIT" --> "𝑻"
  , "MIU" --> "𝑼"
  , "MIV" --> "𝑽"
  , "MIW" --> "𝑾"
  , "MIX" --> "𝑿"
  , "MIY" --> "𝒀"
  , "MIZ" --> "𝒁"
  
  , "MIa" --> "𝒂"
  , "MIb" --> "𝒃"
  , "MIc" --> "𝒄"
  , "MId" --> "𝒅"
  , "MIe" --> "𝒆"
  , "MIf" --> "𝒇"
  , "MIg" --> "𝒈"
  , "MIh" --> "𝒉"
  , "MIi" --> "𝒊"
  , "MIj" --> "𝒋"
  , "MIk" --> "𝒌"
  , "MIl" --> "𝒍"
  , "MIm" --> "𝒎"
  , "MIn" --> "𝒏"
  , "MIo" --> "𝒐"
  , "MIp" --> "𝒑"
  , "MIq" --> "𝒒"
  , "MIr" --> "𝒓"
  , "MIs" --> "𝒔"
  , "MIt" --> "𝒕"
  , "MIu" --> "𝒖"
  , "MIv" --> "𝒗"
  , "MIw" --> "𝒘"
  , "MIx" --> "𝒙"
  , "MIy" --> "𝒚"
  , "MIz" --> "𝒛"
  
  , "McA" --> "𝒜"
  , "McB" --> "ℬ"
  , "McC" --> "𝒞"
  , "McD" --> "𝒟"
  , "McE" --> "ℰ"
  , "McF" --> "ℱ"
  , "McG" --> "𝒢"
  , "McH" --> "ℋ"
  , "McI" --> "ℐ"
  , "McJ" --> "𝒥"
  , "McK" --> "𝒦"
  , "McL" --> "ℒ"
  , "McM" --> "ℳ"
  , "McN" --> "𝒩"
  , "McO" --> "𝒪"
  , "McP" --> "𝒫"
  , "McQ" --> "𝒬"
  , "McR" --> "ℛ"
  , "McS" --> "𝒮"
  , "McT" --> "𝒯"
  , "McU" --> "𝒰"
  , "McV" --> "𝒱"
  , "McW" --> "𝒲"
  , "McX" --> "𝒳"
  , "McY" --> "𝒴"
  , "McZ" --> "𝒵"
  
  , "Mca" --> "𝒶"
  , "Mcb" --> "𝒷"
  , "Mcc" --> "𝒸"
  , "Mcd" --> "𝒹"
  , "Mce" --> "ℯ"
  , "Mcf" --> "𝒻"
  , "Mcg" --> "ℊ"
  , "Mch" --> "𝒽"
  , "Mci" --> "𝒾"
  , "Mcj" --> "𝒿"
  , "Mck" --> "𝓀"
  , "Mcl" --> "𝓁"
  , "Mcm" --> "𝓂"
  , "Mcn" --> "𝓃"
  , "Mco" --> "ℴ"
  , "Mcp" --> "𝓅"
  , "Mcq" --> "𝓆"
  , "Mcr" --> "𝓇"
  , "Mcs" --> "𝓈"
  , "Mct" --> "𝓉"
  , "Mcu" --> "𝓊"
  , "Mcv" --> "𝓋"
  , "Mcw" --> "𝓌"
  , "Mcx" --> "𝓍"
  , "Mcy" --> "𝓎"
  , "Mcz" --> "𝓏"
  
  , "MCA" --> "𝓐"
  , "MCB" --> "𝓑"
  , "MCC" --> "𝓒"
  , "MCD" --> "𝓓"
  , "MCE" --> "𝓔"
  , "MCF" --> "𝓕"
  , "MCG" --> "𝓖"
  , "MCH" --> "𝓗"
  , "MCI" --> "𝓘"
  , "MCJ" --> "𝓙"
  , "MCK" --> "𝓚"
  , "MCL" --> "𝓛"
  , "MCM" --> "𝓜"
  , "MCN" --> "𝓝"
  , "MCO" --> "𝓞"
  , "MCP" --> "𝓟"
  , "MCQ" --> "𝓠"
  , "MCR" --> "𝓡"
  , "MCS" --> "𝓢"
  , "MCT" --> "𝓣"
  , "MCU" --> "𝓤"
  , "MCV" --> "𝓥"
  , "MCW" --> "𝓦"
  , "MCX" --> "𝓧"
  , "MCY" --> "𝓨"
  , "MCZ" --> "𝓩"
  
  , "MCa" --> "𝓪"
  , "MCb" --> "𝓫"
  , "MCc" --> "𝓬"
  , "MCd" --> "𝓭"
  , "MCe" --> "𝓮"
  , "MCf" --> "𝓯"
  , "MCg" --> "𝓰"
  , "MCh" --> "𝓱"
  , "MCi" --> "𝓲"
  , "MCj" --> "𝓳"
  , "MCk" --> "𝓴"
  , "MCl" --> "𝓵"
  , "MCm" --> "𝓶"
  , "MCn" --> "𝓷"
  , "MCo" --> "𝓸"
  , "MCp" --> "𝓹"
  , "MCq" --> "𝓺"
  , "MCr" --> "𝓻"
  , "MCs" --> "𝓼"
  , "MCt" --> "𝓽"
  , "MCu" --> "𝓾"
  , "MCv" --> "𝓿"
  , "MCw" --> "𝔀"
  , "MCx" --> "𝔁"
  , "MCy" --> "𝔂"
  , "MCz" --> "𝔃"
  
  , "MfA" --> "𝔄"
  , "MfB" --> "𝔅"
  , "MfC" --> "ℭ"
  , "MfD" --> "𝔇"
  , "MfE" --> "𝔈"
  , "MfF" --> "𝔉"
  , "MfG" --> "𝔊"
  , "MfH" --> "ℌ"
  , "MfI" --> "ℑ"
  , "MfJ" --> "𝔍"
  , "MfK" --> "𝔎"
  , "MfL" --> "𝔏"
  , "MfM" --> "𝔐"
  , "MfN" --> "𝔑"
  , "MfO" --> "𝔒"
  , "MfP" --> "𝔓"
  , "MfQ" --> "𝔔"
  , "MfR" --> "ℜ"
  , "MfS" --> "𝔖"
  , "MfT" --> "𝔗"
  , "MfU" --> "𝔘"
  , "MfV" --> "𝔙"
  , "MfW" --> "𝔚"
  , "MfX" --> "𝔛"
  , "MfY" --> "𝔜"
  , "MfZ" --> "ℨ"
  
  , "Mfa" --> "𝔞"
  , "Mfb" --> "𝔟"
  , "Mfc" --> "𝔠"
  , "Mfd" --> "𝔡"
  , "Mfe" --> "𝔢"
  , "Mff" --> "𝔣"
  , "Mfg" --> "𝔤"
  , "Mfh" --> "𝔥"
  , "Mfi" --> "𝔦"
  , "Mfj" --> "𝔧"
  , "Mfk" --> "𝔨"
  , "Mfl" --> "𝔩"
  , "Mfm" --> "𝔪"
  , "Mfn" --> "𝔫"
  , "Mfo" --> "𝔬"
  , "Mfp" --> "𝔭"
  , "Mfq" --> "𝔮"
  , "Mfr" --> "𝔯"
  , "Mfs" --> "𝔰"
  , "Mft" --> "𝔱"
  , "Mfu" --> "𝔲"
  , "Mfv" --> "𝔳"
  , "Mfw" --> "𝔴"
  , "Mfx" --> "𝔵"
  , "Mfy" --> "𝔶"
  , "Mfz" --> "𝔷"
  ]
