module Symbols where

(-->) :: a -> b -> (a,b)
(-->) = (,)

-- | LaTeX-Compatible Symbols
latexUnaryOperator :: [(String, String)]
latexUnaryOperator =
  [ "neg" --> "¬"
  ]

latexRelation :: [(String, String)]
latexRelation =
  [ "leq" --> "≤"
  , "leqq" --> "≦"
  , "leqslant" --> "⩽"
  , "lesssim" --> "≲"
  , "lessapprox" --> "⪅"
  , "prec" --> "≺"
  , "preceq" --> "⪯" -- ≼
  , "precsim" --> "≾"

  , "geq" --> "≥"
  , "geqq" --> "≧"
  , "geqslant" --> "⩾"
  , "gtrsim" --> "≳"
  , "gtrapprox" --> "⪆"
  , "succ" --> "≻"
  , "succeq" --> "⪰" -- ≽
  , "succsim" --> "≿"

  , "nless" --> "≮"
  , "nleq" --> "≰"
  , "lneq" --> "⪇"
  , "lneqq" --> "≨"
  , "lnsim" --> "⋦"
  , "lnapprox" --> "⪉"
  , "nprec" --> "⊀"
  , "npreceq" --> "⪯̸" -- ⋠
  -- no nleqslant

  , "ngtr" --> "≯"
  , "ngeq" --> "≱"
  , "gneq" --> "⪈"
  , "gneqq" --> "≩"
  , "gnsim" --> "⋧"
  , "gnapprox" --> "⪊"
  , "nsucc" --> "⊁"
  , "nsucceq" --> "⪰̸" -- ⋡
  -- no ngeqslant
  
  , "ll" --> "≪"
  , "lll" --> "⋘"

  , "gg" --> "≫"
  , "ggg" --> "⋙"
  
  , "lessgtr" --> "≶"
  , "lesseqgtr" --> "⋚"

  , "subset" --> "⊂"
  , "subseteq" --> "⊆"
  , "sqsubset" --> "⊏"
  , "sqsubseteq" --> "⊑"
  
  , "nsubset" --> "⊄"
  , "nsubseteq" --> "⊈"
  , "subsetneq" --> "⊊"
  
  , "supset" --> "⊃"
  , "supseteq" --> "⊇"
  , "sqsupset" --> "⊐"
  , "sqsupseteq" --> "⊒"
  
  , "nsupset" --> "⊅"
  , "nsupseteq" --> "⊉"
  , "supsetneq" --> "⊋"

  , "doteq" --> "≐"
  , "equiv" --> "≡"
  , "approx" --> "≈"
  , "cong" --> "≅"
  , "simeq" --> "≃"
  , "sim" --> "∼"
  , "propto" --> "∝"
  
  , "neq" --> "≠"
  , "nequiv" --> "≢"
  , "napprox" --> "≉"
  , "ncong" --> "≇"
  , "nsimeq" --> "≄"
  , "nsim" --> "≁"
  ]

latexArrow :: [(String, String)]
latexArrow =
  [ "to" --> "→"
  , "rightarrow" --> "→"
  , "Rightarrow" --> "⇒"
  , "longrightarrow" --> "⟶"
  
  , "gets" --> "←"
  , "leftarrow" --> "←"
  , "Leftarrow" --> "⇐"
  , "longleftarrow" --> "⟵"
  
  , "mapsto" --> "↦"
  , "longmapsto" --> "⟼"

  , "uparrow" --> "↑"
  , "downaroow" --> "↓"
  , "updownarrow" --> "↕"
  
  , "Uparrow" --> "⇑"
  , "Downarrow" --> "⇓"
  , "Updownarrow" --> "⇕"
  ]

latexMisc :: [(String, String)]
latexMisc =
  [ "partial" --> "∂"
  , "nabla" --> "∇"
  , "imath" --> "ı"
  , "jmath" --> "ȷ"
  , "ell" --> "ℓ"
  , "Re" --> "ℜ"
  , "Im" --> "ℑ"
  , "infty" --> "∞"
  , "wp" --> "℘"
  , "hbar" --> "ℏ"
  , "hslash" --> "ℏ"
  ]

latexHebrew :: [(String, String)]
latexHebrew =
  [ "aleph" --> "ℵ"
  , "beth" --> "ℶ"
  , "gimel" --> "ℷ"
  ]

latexParenthesis :: [(String, String)]
latexParenthesis =
  [ "langle" --> "⟨"
  , "rangle" --> "⟩"
  , "lfloor" --> "⌊"
  , "rfloor" --> "⌋"
  , "lceil" --> "⌈"
  , "rceil" --> "⌉"
  
  , "|" --> "‖"
  ]

-- | Non-LaTeX Symbols
 

parenthesis :: [(String, String)]
parenthesis =
  [ "[[" --> "⟦"
  , "]]" --> "⟧"
  , "<"  --> "⟨"
  , ">"  --> "⟩"
  , "<<" --> "⟪"
  , ">>" --> "⟫"
  , "{{" --> "⦃"
  , "}}" --> "⦄"
  , "(|" --> "⦇"
  , "|)" --> "⦈"
  , "((" --> "⦅"
  , "))" --> "⦆"
  
  , "(b" --> "⟅"
  , ")b" --> "⟆"
  , "lbag" --> "⟅"
  , "rbag" --> "⟆"
  ]

greek :: [(String, String)]
greek =
  [ "Alpha"      --> "\x0391"
  , "Beta"       --> "\x0392"
  , "Gammma"     --> "\x0393"
  , "Delta"      --> "\x0394"
  , "Epsilon"    --> "\x0395"
  , "Zeta"       --> "\x0396"
  , "Eta"        --> "\x0397"
  , "Theta"      --> "\x0398"
  , "Iota"       --> "\x0399"
  , "Kappa"      --> "\x039a"
  , "Lambda"     --> "\x039b"
  , "Mu"         --> "\x039c"
  , "Nu"         --> "\x039d"
  , "Xi"         --> "\x039e"
  , "Omicron"    --> "\x039f"
  , "Pi"         --> "\x03a0"
  , "Rho"        --> "\x03a1"
  , "Sigma"      --> "\x03a2"
  , "Tau"        --> "\x03a3"
  , "Upsilon"    --> "\x03a4"
  , "Phi"        --> "\x03a5"
  , "Chi"        --> "\x03a6"
  , "Psi"        --> "\x03a7"
  , "Omega"      --> "\x03a8"

  , "alpha"      --> "\x03b1"
  , "beta"       --> "\x03b2"
  , "gamma"      --> "\x03b3"
  , "delta"      --> "\x03b4"
  , "varepsilon" --> "\x03b5"
  , "zeta"       --> "\x03b6"
  , "eta"        --> "\x03b7"
  , "theta"      --> "\x03b8"
  , "iota"       --> "\x03b9"
  , "kappa"      --> "\x03ba"
  , "lambda"     --> "\x03bb"
  , "mu"         --> "\x03bc"
  , "nu"         --> "\x03bd"
  , "xi"         --> "\x03be"
  , "omicron"    --> "\x03bf"
  , "pi"         --> "\x03c0"
  , "rho"        --> "\x03c1"
  , "varsigma"   --> "\x03c2"
  , "sigma"      --> "\x03c3"
  , "tau"        --> "\x03c4"
  , "upsilon"    --> "\x03c5"
  , "varphi"     --> "\x03c6" -- φ
  , "chi"        --> "\x03c7"
  , "psi"        --> "\x03c8"
  , "omega"      --> "\x03c9"

  , "vartheta"   --> "\x03d1"
  , "phi"        --> "\x03d5" -- ϕ
  , "varpi"      --> "\x03d6"
  , "Digamma"    --> "\x03dc"
  , "digamma"    --> "\x03dd"
  , "varkappa"   --> "\x03f0"
  , "varrho"     --> "\x03f1"
  , "varTheta"   --> "\x03f4"
  , "epsilon"    --> "\x03f5"
  ]

-- | Mathematical Alphanumeric Symbols
-- bold
-- italic
-- bold italic
-- script
-- bold script
-- fraktur
-- double-struck
-- bold fraktur
-- sans-serif
-- sans-serif bold
-- sans-serif italic
-- sans-serif bold italic
-- monospace

-- italic dotless
  
-- bold greek
-- italic greek
-- bold italic greek
-- sans-serif bold greek
-- sans-serif bold italic greek
-- bold digamma

-- bold digit
-- double-struck digit
-- sans-serif digit
-- sans-serif bold digit
-- monospace digit

mathBold :: [(String, String)]
mathBold =
  [ "A" --> "\x1d400" -- 𝐀
  , "B" --> "\x1d401"
  , "C" --> "\x1d402"
  , "D" --> "\x1d403"
  , "E" --> "\x1d404"
  , "F" --> "\x1d405"
  , "G" --> "\x1d406"
  , "H" --> "\x1d407"
  , "I" --> "\x1d408"
  , "J" --> "\x1d409"
  , "K" --> "\x1d40a"
  , "L" --> "\x1d40b"
  , "M" --> "\x1d40c"
  , "N" --> "\x1d40d"
  , "O" --> "\x1d40e"
  , "P" --> "\x1d40f"
  , "Q" --> "\x1d410"
  , "R" --> "\x1d411"
  , "S" --> "\x1d412"
  , "T" --> "\x1d413"
  , "U" --> "\x1d414"
  , "V" --> "\x1d415"
  , "W" --> "\x1d416"
  , "X" --> "\x1d417"
  , "Y" --> "\x1d418"
  , "Z" --> "\x1d419"

  , "a" --> "\x1d41a"
  , "b" --> "\x1d41b"
  , "c" --> "\x1d41c"
  , "d" --> "\x1d41d"
  , "e" --> "\x1d41e"
  , "f" --> "\x1d41f"
  , "g" --> "\x1d420"
  , "h" --> "\x1d421"
  , "i" --> "\x1d422"
  , "j" --> "\x1d423"
  , "k" --> "\x1d424"
  , "l" --> "\x1d425"
  , "m" --> "\x1d426"
  , "n" --> "\x1d427"
  , "o" --> "\x1d428"
  , "p" --> "\x1d429"
  , "q" --> "\x1d42a"
  , "r" --> "\x1d42b"
  , "s" --> "\x1d42c"
  , "t" --> "\x1d42d"
  , "u" --> "\x1d42e"
  , "v" --> "\x1d42f"
  , "w" --> "\x1d430"
  , "x" --> "\x1d431"
  , "y" --> "\x1d432"
  , "z" --> "\x1d433"
  ]

mathItalic :: [(String, String)]
mathItalic =
  [ "A" --> "\x1d434" -- 𝐴
  , "B" --> "\x1d435" -- 𝐵
  , "C" --> "\x1d436" -- 𝐶
  , "D" --> "\x1d437" -- 𝐷
  , "E" --> "\x1d438" -- 𝐸
  , "F" --> "\x1d439" -- 𝐹
  , "G" --> "\x1d43a" -- 𝐺
  , "H" --> "\x1d43b" -- 𝐻
  , "I" --> "\x1d43c" -- 𝐼
  , "J" --> "\x1d43d" -- 𝐽
  , "K" --> "\x1d43e" -- 𝐾
  , "L" --> "\x1d43f" -- 𝐿
  , "M" --> "\x1d440" -- 𝑀
  , "N" --> "\x1d441" -- 𝑁
  , "O" --> "\x1d442" -- 𝑂
  , "P" --> "\x1d443" -- 𝑃
  , "Q" --> "\x1d444" -- 𝑄
  , "R" --> "\x1d445" -- 𝑅
  , "S" --> "\x1d446" -- 𝑆
  , "T" --> "\x1d447" -- 𝑇
  , "U" --> "\x1d448" -- 𝑈
  , "V" --> "\x1d449" -- 𝑉
  , "W" --> "\x1d44a" -- 𝑊
  , "X" --> "\x1d44b" -- 𝑋
  , "Y" --> "\x1d44c" -- 𝑌
  , "Z" --> "\x1d44d" -- 𝑍

  , "a" --> "\x1d44e" -- 𝑎
  , "b" --> "\x1d44f" -- 𝑏
  , "c" --> "\x1d450" -- 𝑐
  , "d" --> "\x1d451" -- 𝑑
  , "e" --> "\x1d452" -- 𝑒
  , "f" --> "\x1d453" -- 𝑓
  , "g" --> "\x1d454" -- 𝑔
  , "h" --> "\x1d455" -- ℎ
  , "i" --> "\x1d456" -- 𝑖
  , "j" --> "\x1d457" -- 𝑗
  , "k" --> "\x1d458" -- 𝑘
  , "l" --> "\x1d459" -- 𝑙
  , "m" --> "\x1d45a" -- 𝑚
  , "n" --> "\x1d45b" -- 𝑛
  , "o" --> "\x1d45c" -- 𝑜
  , "p" --> "\x1d45d" -- 𝑝
  , "q" --> "\x1d45e" -- 𝑞
  , "r" --> "\x1d45f" -- 𝑟
  , "s" --> "\x1d460" -- 𝑠
  , "t" --> "\x1d461" -- 𝑡
  , "u" --> "\x1d462" -- 𝑢
  , "v" --> "\x1d463" -- 𝑣
  , "w" --> "\x1d464" -- 𝑤
  , "x" --> "\x1d465" -- 𝑥
  , "y" --> "\x1d466" -- 𝑦
  , "z" --> "\x1d467" -- 𝑧
  ]

mathBoldItalic :: [(String, String)]
mathBoldItalic =
  [ "A" --> "𝑨"
  , "B" --> "𝑩"
  , "C" --> "𝑪"
  , "D" --> "𝑫"
  , "E" --> "𝑬"
  , "F" --> "𝑭"
  , "G" --> "𝑮"
  , "H" --> "𝑯"
  , "I" --> "𝑰"
  , "J" --> "𝑱"
  , "K" --> "𝑲"
  , "L" --> "𝑳"
  , "M" --> "𝑴"
  , "N" --> "𝑵"
  , "O" --> "𝑶"
  , "P" --> "𝑷"
  , "Q" --> "𝑸"
  , "R" --> "𝑹"
  , "S" --> "𝑺"
  , "T" --> "𝑻"
  , "U" --> "𝑼"
  , "V" --> "𝑽"
  , "W" --> "𝑾"
  , "X" --> "𝑿"
  , "Y" --> "𝒀"
  , "Z" --> "𝒁"
  
  , "a" --> "𝒂"
  , "b" --> "𝒃"
  , "c" --> "𝒄"
  , "d" --> "𝒅"
  , "e" --> "𝒆"
  , "f" --> "𝒇"
  , "g" --> "𝒈"
  , "h" --> "𝒉"
  , "i" --> "𝒊"
  , "j" --> "𝒋"
  , "k" --> "𝒌"
  , "l" --> "𝒍"
  , "m" --> "𝒎"
  , "n" --> "𝒏"
  , "o" --> "𝒐"
  , "p" --> "𝒑"
  , "q" --> "𝒒"
  , "r" --> "𝒓"
  , "s" --> "𝒔"
  , "t" --> "𝒕"
  , "u" --> "𝒖"
  , "v" --> "𝒗"
  , "w" --> "𝒘"
  , "x" --> "𝒙"
  , "y" --> "𝒚"
  , "z" --> "𝒛"
  ]

mathScript :: [(String, String)]
mathScript =
  [ "A" --> "𝒜"
  , "B" --> "ℬ"
  , "C" --> "𝒞"
  , "D" --> "𝒟"
  , "E" --> "ℰ"
  , "F" --> "ℱ"
  , "G" --> "𝒢"
  , "H" --> "ℋ"
  , "I" --> "ℐ"
  , "J" --> "𝒥"
  , "K" --> "𝒦"
  , "L" --> "ℒ"
  , "M" --> "ℳ"
  , "N" --> "𝒩"
  , "O" --> "𝒪"
  , "P" --> "𝒫"
  , "Q" --> "𝒬"
  , "R" --> "ℛ"
  , "S" --> "𝒮"
  , "T" --> "𝒯"
  , "U" --> "𝒰"
  , "V" --> "𝒱"
  , "W" --> "𝒲"
  , "X" --> "𝒳"
  , "Y" --> "𝒴"
  , "Z" --> "𝒵"

  , "a" --> "𝒶"
  , "b" --> "𝒷"
  , "c" --> "𝒸"
  , "d" --> "𝒹"
  , "e" --> "ℯ"
  , "f" --> "𝒻"
  , "g" --> "ℊ"
  , "h" --> "𝒽"
  , "i" --> "𝒾"
  , "j" --> "𝒿"
  , "k" --> "𝓀"
  , "l" --> "𝓁"
  , "m" --> "𝓂"
  , "n" --> "𝓃"
  , "o" --> "ℴ"
  , "p" --> "𝓅"
  , "q" --> "𝓆"
  , "r" --> "𝓇"
  , "s" --> "𝓈"
  , "t" --> "𝓉"
  , "u" --> "𝓊"
  , "v" --> "𝓋"
  , "w" --> "𝓌"
  , "x" --> "𝓍"
  , "y" --> "𝓎"
  , "z" --> "𝓏"
  ]

mathBoldScript :: [(String, String)]
mathBoldScript =
  [ "A" --> "𝓐"
  , "B" --> "𝓑"
  , "C" --> "𝓒"
  , "D" --> "𝓓"
  , "E" --> "𝓔"
  , "F" --> "𝓕"
  , "G" --> "𝓖"
  , "H" --> "𝓗"
  , "I" --> "𝓘"
  , "J" --> "𝓙"
  , "K" --> "𝓚"
  , "L" --> "𝓛"
  , "M" --> "𝓜"
  , "N" --> "𝓝"
  , "O" --> "𝓞"
  , "P" --> "𝓟"
  , "Q" --> "𝓠"
  , "R" --> "𝓡"
  , "S" --> "𝓢"
  , "T" --> "𝓣"
  , "U" --> "𝓤"
  , "V" --> "𝓥"
  , "W" --> "𝓦"
  , "X" --> "𝓧"
  , "Y" --> "𝓨"
  , "Z" --> "𝓩"

  , "a" --> "𝓪"
  , "b" --> "𝓫"
  , "c" --> "𝓬"
  , "d" --> "𝓭"
  , "e" --> "𝓮"
  , "f" --> "𝓯"
  , "g" --> "𝓰"
  , "h" --> "𝓱"
  , "i" --> "𝓲"
  , "j" --> "𝓳"
  , "k" --> "𝓴"
  , "l" --> "𝓵"
  , "m" --> "𝓶"
  , "n" --> "𝓷"
  , "o" --> "𝓸"
  , "p" --> "𝓹"
  , "q" --> "𝓺"
  , "r" --> "𝓻"
  , "s" --> "𝓼"
  , "t" --> "𝓽"
  , "u" --> "𝓾"
  , "v" --> "𝓿"
  , "w" --> "𝔀"
  , "x" --> "𝔁"
  , "y" --> "𝔂"
  , "z" --> "𝔃"
  ]

matheFraktur :: [(String, String)]
matheFraktur =
  [ "A" --> "𝔄"
  , "B" --> "𝔅"
  , "C" --> "ℭ"
  , "D" --> "𝔇"
  , "E" --> "𝔈"
  , "F" --> "𝔉"
  , "G" --> "𝔊"
  , "H" --> "ℌ"
  , "I" --> "ℑ"
  , "J" --> "𝔍"
  , "K" --> "𝔎"
  , "L" --> "𝔏"
  , "M" --> "𝔐"
  , "N" --> "𝔑"
  , "O" --> "𝔒"
  , "P" --> "𝔓"
  , "Q" --> "𝔔"
  , "R" --> "ℜ"
  , "S" --> "𝔖"
  , "T" --> "𝔗"
  , "U" --> "𝔘"
  , "V" --> "𝔙"
  , "W" --> "𝔚"
  , "X" --> "𝔛"
  , "Y" --> "𝔜"
  , "Z" --> "ℨ"

  , "a" --> "𝔞"
  , "b" --> "𝔟"
  , "c" --> "𝔠"
  , "d" --> "𝔡"
  , "e" --> "𝔢"
  , "f" --> "𝔣"
  , "g" --> "𝔤"
  , "h" --> "𝔥"
  , "i" --> "𝔦"
  , "j" --> "𝔧"
  , "k" --> "𝔨"
  , "l" --> "𝔩"
  , "m" --> "𝔪"
  , "n" --> "𝔫"
  , "o" --> "𝔬"
  , "p" --> "𝔭"
  , "q" --> "𝔮"
  , "r" --> "𝔯"
  , "s" --> "𝔰"
  , "t" --> "𝔱"
  , "u" --> "𝔲"
  , "v" --> "𝔳"
  , "w" --> "𝔴"
  , "x" --> "𝔵"
  , "y" --> "𝔶"
  , "z" --> "𝔷"
  ]

mathDoubleStruck :: [(String, String)]
mathDoubleStruck =
  [ "A" --> "𝔸"
  , "B" --> "𝔹"
  , "C" --> "ℂ"
  , "D" --> "𝔻"
  , "E" --> "𝔼"
  , "F" --> "𝔽"
  , "G" --> "𝔾"
  , "H" --> "ℍ"
  , "I" --> "𝕀"
  , "J" --> "𝕁"
  , "K" --> "𝕂"
  , "L" --> "𝕃"
  , "M" --> "𝕄"
  , "N" --> "ℕ"
  , "O" --> "𝕆"
  , "P" --> "ℙ"
  , "Q" --> "ℚ"
  , "R" --> "ℝ"
  , "S" --> "𝕊"
  , "T" --> "𝕋"
  , "U" --> "𝕌"
  , "V" --> "𝕍"
  , "W" --> "𝕎"
  , "X" --> "𝕏"
  , "Y" --> "𝕐"
  , "Z" --> "ℤ"

  , "a" --> "𝕒"
  , "b" --> "𝕓"
  , "c" --> "𝕔"
  , "d" --> "𝕕"
  , "e" --> "𝕖"
  , "f" --> "𝕗"
  , "g" --> "𝕘"
  , "h" --> "𝕙"
  , "i" --> "𝕚"
  , "j" --> "𝕛"
  , "k" --> "𝕜"
  , "l" --> "𝕝"
  , "m" --> "𝕞"
  , "n" --> "𝕟"
  , "o" --> "𝕠"
  , "p" --> "𝕡"
  , "q" --> "𝕢"
  , "r" --> "𝕣"
  , "s" --> "𝕤"
  , "t" --> "𝕥"
  , "u" --> "𝕦"
  , "v" --> "𝕧"
  , "w" --> "𝕨"
  , "x" --> "𝕩"
  , "y" --> "𝕪"
  , "z" --> "𝕫"
  ]

mathBoldFraktur :: [(String, String)]
mathBoldFraktur =
  [ "A" --> "\x1d56c"
  , "B" --> "\x1d56d"
  , "C" --> "\x1d56e"
  , "D" --> "\x1d56f"
  , "E" --> "\x1d570"
  , "F" --> "\x1d571"
  , "G" --> "\x1d572"
  , "H" --> "\x1d573"
  , "I" --> "\x1d574"
  , "J" --> "\x1d575"
  , "K" --> "\x1d576"
  , "L" --> "\x1d577"
  , "M" --> "\x1d578"
  , "N" --> "\x1d579"
  , "O" --> "\x1d57a"
  , "P" --> "\x1d57b"
  , "Q" --> "\x1d57c"
  , "R" --> "\x1d57d"
  , "S" --> "\x1d57e"
  , "T" --> "\x1d57f"
  , "U" --> "\x1d580"
  , "V" --> "\x1d581"
  , "W" --> "\x1d582"
  , "X" --> "\x1d583"
  , "Y" --> "\x1d584"
  , "Z" --> "\x1d585"

  , "a" --> "\x1d586"
  , "b" --> "\x1d587"
  , "c" --> "\x1d588"
  , "d" --> "\x1d589"
  , "e" --> "\x1d58a"
  , "f" --> "\x1d58b"
  , "g" --> "\x1d58c"
  , "h" --> "\x1d58d"
  , "i" --> "\x1d58e"
  , "j" --> "\x1d58f"
  , "k" --> "\x1d590"
  , "l" --> "\x1d591"
  , "m" --> "\x1d592"
  , "n" --> "\x1d593"
  , "o" --> "\x1d594"
  , "p" --> "\x1d595"
  , "q" --> "\x1d596"
  , "r" --> "\x1d597"
  , "s" --> "\x1d598"
  , "t" --> "\x1d599"
  , "u" --> "\x1d59a"
  , "v" --> "\x1d59b"
  , "w" --> "\x1d59c"
  , "x" --> "\x1d59d"
  , "y" --> "\x1d59e"
  , "z" --> "\x1d59f"
  ]
  
mathSansSerif :: [(String, String)]
mathSansSerif =
  [ "A" --> "\x1d5a0"
  , "B" --> "\x1d5a1"
  , "C" --> "\x1d5a2"
  , "D" --> "\x1d5a3"
  , "E" --> "\x1d5a4"
  , "F" --> "\x1d5a5"
  , "G" --> "\x1d5a6"
  , "H" --> "\x1d5a7"
  , "I" --> "\x1d5a8"
  , "J" --> "\x1d5a9"
  , "K" --> "\x1d5aa"
  , "L" --> "\x1d5ab"
  , "M" --> "\x1d5ac"
  , "N" --> "\x1d5ad"
  , "O" --> "\x1d5ae"
  , "P" --> "\x1d5af"
  , "Q" --> "\x1d5b0"
  , "R" --> "\x1d5b1"
  , "S" --> "\x1d5b2"
  , "T" --> "\x1d5b3"
  , "U" --> "\x1d5b4"
  , "V" --> "\x1d5b5"
  , "W" --> "\x1d5b6"
  , "X" --> "\x1d5b7"
  , "Y" --> "\x1d5b8"
  , "Z" --> "\x1d5b9"

  , "a" --> "\x1d5ba"
  , "b" --> "\x1d5bb"
  , "c" --> "\x1d5bc"
  , "d" --> "\x1d5bd"
  , "e" --> "\x1d5be"
  , "f" --> "\x1d5bf"
  , "g" --> "\x1d5c0"
  , "h" --> "\x1d5c1"
  , "i" --> "\x1d5c2"
  , "j" --> "\x1d5c3"
  , "k" --> "\x1d5c4"
  , "l" --> "\x1d5c5"
  , "m" --> "\x1d5c6"
  , "n" --> "\x1d5c7"
  , "o" --> "\x1d5c8"
  , "p" --> "\x1d5c9"
  , "q" --> "\x1d5ca"
  , "r" --> "\x1d5cb"
  , "s" --> "\x1d5cc"
  , "t" --> "\x1d5cd"
  , "u" --> "\x1d5ce"
  , "v" --> "\x1d5cf"
  , "w" --> "\x1d5d0"
  , "x" --> "\x1d5d1"
  , "y" --> "\x1d5d2"
  , "z" --> "\x1d5d3"
  ]
  
mathSansSerifBold :: [(String, String)]
mathSansSerifBold =
  [ "A" --> "\x1d5d4"
  , "B" --> "\x1d5d5"
  , "C" --> "\x1d5d6"
  , "D" --> "\x1d5d7"
  , "E" --> "\x1d5d8"
  , "F" --> "\x1d5d9"
  , "G" --> "\x1d5da"
  , "H" --> "\x1d5db"
  , "I" --> "\x1d5dc"
  , "J" --> "\x1d5dd"
  , "K" --> "\x1d5de"
  , "L" --> "\x1d5df"
  , "M" --> "\x1d5e0"
  , "N" --> "\x1d5e1"
  , "O" --> "\x1d5e2"
  , "P" --> "\x1d5e3"
  , "Q" --> "\x1d5e4"
  , "R" --> "\x1d5e5"
  , "S" --> "\x1d5e6"
  , "T" --> "\x1d5e7"
  , "U" --> "\x1d5e8"
  , "V" --> "\x1d5e9"
  , "W" --> "\x1d5ea"
  , "X" --> "\x1d5eb"
  , "Y" --> "\x1d5ec"
  , "Z" --> "\x1d5ed"

  , "a" --> "\x1d5ee"
  , "b" --> "\x1d5ef"
  , "c" --> "\x1d5f0"
  , "d" --> "\x1d5f1"
  , "e" --> "\x1d5f2"
  , "f" --> "\x1d5f3"
  , "g" --> "\x1d5f4"
  , "h" --> "\x1d5f5"
  , "i" --> "\x1d5f6"
  , "j" --> "\x1d5f7"
  , "k" --> "\x1d5f8"
  , "l" --> "\x1d5f9"
  , "m" --> "\x1d6fa"
  , "n" --> "\x1d5fb"
  , "o" --> "\x1d5fc"
  , "p" --> "\x1d5fd"
  , "q" --> "\x1d5fe"
  , "r" --> "\x1d5ff"
  , "s" --> "\x1d600"
  , "t" --> "\x1d601"
  , "u" --> "\x1d602"
  , "v" --> "\x1d603"
  , "w" --> "\x1d604"
  , "x" --> "\x1d605"
  , "y" --> "\x1d606"
  , "z" --> "\x1d607"
  ]

mathSansSerifItalic :: [(String, String)]
mathSansSerifItalic =
  [ "A" --> "\x1d608"
  , "B" --> "\x1d609"
  , "C" --> "\x1d60a"
  , "D" --> "\x1d60b"
  , "E" --> "\x1d60c"
  , "F" --> "\x1d60d"
  , "G" --> "\x1d60e"
  , "H" --> "\x1d60f"
  , "I" --> "\x1d610"
  , "J" --> "\x1d611"
  , "K" --> "\x1d612"
  , "L" --> "\x1d613"
  , "M" --> "\x1d614"
  , "N" --> "\x1d615"
  , "O" --> "\x1d616"
  , "P" --> "\x1d617"
  , "Q" --> "\x1d618"
  , "R" --> "\x1d619"
  , "S" --> "\x1d61a"
  , "T" --> "\x1d61b"
  , "U" --> "\x1d61c"
  , "V" --> "\x1d61d"
  , "W" --> "\x1d61e"
  , "X" --> "\x1d61f"
  , "Y" --> "\x1d620"
  , "Z" --> "\x1d621"

  , "a" --> "\x1d622"
  , "b" --> "\x1d623"
  , "c" --> "\x1d624"
  , "d" --> "\x1d625"
  , "e" --> "\x1d626"
  , "f" --> "\x1d627"
  , "g" --> "\x1d628"
  , "h" --> "\x1d629"
  , "i" --> "\x1d62a"
  , "j" --> "\x1d62b"
  , "k" --> "\x1d62c"
  , "l" --> "\x1d62d"
  , "m" --> "\x1d62e"
  , "n" --> "\x1d62f"
  , "o" --> "\x1d630"
  , "p" --> "\x1d631"
  , "q" --> "\x1d632"
  , "r" --> "\x1d633"
  , "s" --> "\x1d634"
  , "t" --> "\x1d635"
  , "u" --> "\x1d636"
  , "v" --> "\x1d637"
  , "w" --> "\x1d638"
  , "x" --> "\x1d639"
  , "y" --> "\x1d63a"
  , "z" --> "\x1d63b"
  ]

mathSansSerifBoldItalic :: [(String, String)]
mathSansSerifBoldItalic =
  [ "A" --> "\x1d63c"
  , "B" --> "\x1d63d"
  , "C" --> "\x1d63e"
  , "D" --> "\x1d63f"
  , "E" --> "\x1d640"
  , "F" --> "\x1d641"
  , "G" --> "\x1d642"
  , "H" --> "\x1d643"
  , "I" --> "\x1d644"
  , "J" --> "\x1d645"
  , "K" --> "\x1d646"
  , "L" --> "\x1d647"
  , "M" --> "\x1d648"
  , "N" --> "\x1d649"
  , "O" --> "\x1d64a"
  , "P" --> "\x1d64b"
  , "Q" --> "\x1d64c"
  , "R" --> "\x1d64d"
  , "S" --> "\x1d64e"
  , "T" --> "\x1d64f"
  , "U" --> "\x1d650"
  , "V" --> "\x1d651"
  , "W" --> "\x1d652"
  , "X" --> "\x1d653"
  , "Y" --> "\x1d654"
  , "Z" --> "\x1d655"

  , "a" --> "\x1d656"
  , "b" --> "\x1d657"
  , "c" --> "\x1d658"
  , "d" --> "\x1d659"
  , "e" --> "\x1d65a"
  , "f" --> "\x1d65b"
  , "g" --> "\x1d65c"
  , "h" --> "\x1d65d"
  , "i" --> "\x1d65e"
  , "j" --> "\x1d65f"
  , "k" --> "\x1d660"
  , "l" --> "\x1d661"
  , "m" --> "\x1d662"
  , "n" --> "\x1d663"
  , "o" --> "\x1d664"
  , "p" --> "\x1d665"
  , "q" --> "\x1d666"
  , "r" --> "\x1d667"
  , "s" --> "\x1d668"
  , "t" --> "\x1d669"
  , "u" --> "\x1d66a"
  , "v" --> "\x1d66b"
  , "w" --> "\x1d66c"
  , "x" --> "\x1d66d"
  , "y" --> "\x1d66e"
  , "z" --> "\x1d66f"
  ]
  
mathSansMonospace :: [(String, String)]
mathSansMonospace =
  [ "A" --> "\x1d670"
  , "B" --> "\x1d671"
  , "C" --> "\x1d672"
  , "D" --> "\x1d673"
  , "E" --> "\x1d674"
  , "F" --> "\x1d675"
  , "G" --> "\x1d676"
  , "H" --> "\x1d677"
  , "I" --> "\x1d678"
  , "J" --> "\x1d679"
  , "K" --> "\x1d67a"
  , "L" --> "\x1d67b"
  , "M" --> "\x1d67c"
  , "N" --> "\x1d67d"
  , "O" --> "\x1d67e"
  , "P" --> "\x1d67f"
  , "Q" --> "\x1d680"
  , "R" --> "\x1d681"
  , "S" --> "\x1d682"
  , "T" --> "\x1d683"
  , "U" --> "\x1d684"
  , "V" --> "\x1d685"
  , "W" --> "\x1d686"
  , "X" --> "\x1d687"
  , "Y" --> "\x1d688"
  , "Z" --> "\x1d689"

  , "a" --> "\x1d68a"
  , "b" --> "\x1d68b"
  , "c" --> "\x1d68c"
  , "d" --> "\x1d68d"
  , "e" --> "\x1d68e"
  , "f" --> "\x1d68f"
  , "g" --> "\x1d690"
  , "h" --> "\x1d691"
  , "i" --> "\x1d692"
  , "j" --> "\x1d693"
  , "k" --> "\x1d694"
  , "l" --> "\x1d695"
  , "m" --> "\x1d696"
  , "n" --> "\x1d697"
  , "o" --> "\x1d698"
  , "p" --> "\x1d699"
  , "q" --> "\x1d69a"
  , "r" --> "\x1d69b"
  , "s" --> "\x1d69c"
  , "t" --> "\x1d69d"
  , "u" --> "\x1d69e"
  , "v" --> "\x1d69f"
  , "w" --> "\x1d6a0"
  , "x" --> "\x1d6a1"
  , "y" --> "\x1d6a2"
  , "z" --> "\x1d6a3"
  ]

mathItalicDotless :: [(String, String)]
mathItalicDotless =
  [ "imath" --> "\x1d6a4" -- "𝚤"
  , "jmath" --> "\x1d6a5" -- "𝚥"
  ]

mathBoldGreek :: [(String, String)]
mathBoldGreek =
  [ "Alpha"      --> "\x1d6a8"
  , "Beta"       --> "\x1d6a9"
  , "Gammma"     --> "\x1d6aa"
  , "Delta"      --> "\x1d6ab"
  , "Epsilon"    --> "\x1d6ac"
  , "Zeta"       --> "\x1d6ad"
  , "Eta"        --> "\x1d6ae"
  , "Theta"      --> "\x1d6af"
  , "Iota"       --> "\x1d6b0"
  , "Kappa"      --> "\x1d6b1"
  , "Lambda"     --> "\x1d6b2"
  , "Mu"         --> "\x1d6b3"
  , "Nu"         --> "\x1d6b4"
  , "Xi"         --> "\x1d6b5"
  , "Omicron"    --> "\x1d6b6"
  , "Pi"         --> "\x1d6b7"
  , "Rho"        --> "\x1d6b8"
  , "varTheta"   --> "\x1d6b9"
  , "Sigma"      --> "\x1d6ba"
  , "Tau"        --> "\x1d6bb"
  , "Upsilon"    --> "\x1d6bc"
  , "Phi"        --> "\x1d6bd"
  , "Chi"        --> "\x1d6be"
  , "Psi"        --> "\x1d6bf"
  , "Omega"      --> "\x1d6c0"
  , "nabla"      --> "\x1d6c1"

  , "alpha"      --> "\x1d6c2"
  , "beta"       --> "\x1d6c3"
  , "gamma"      --> "\x1d6c4"
  , "delta"      --> "\x1d6c5"
  , "varepsilon" --> "\x1d6c6"
  , "zeta"       --> "\x1d6c7"
  , "eta"        --> "\x1d6c8"
  , "theta"      --> "\x1d6c9"
  , "iota"       --> "\x1d6ca"
  , "kappa"      --> "\x1d6cb"
  , "lambda"     --> "\x1d6cc"
  , "mu"         --> "\x1d6cd"
  , "nu"         --> "\x1d6ce"
  , "xi"         --> "\x1d6cf"
  , "omicron"    --> "\x1d6d0"
  , "pi"         --> "\x1d6d1"
  , "rho"        --> "\x1d6d2"
  , "varsigma"   --> "\x1d6d3"
  , "sigma"      --> "\x1d6d4"
  , "tau"        --> "\x1d6d5"
  , "upsilon"    --> "\x1d6d6"
  , "varphi"     --> "\x1d6d7"
  , "chi"        --> "\x1d6d8"
  , "psi"        --> "\x1d6d9"
  , "omega"      --> "\x1d6da"

  , "partial"    --> "\x1d6db"
  , "epsilon"    --> "\x1d6dc"
  , "vartheta"   --> "\x1d6dd"
  , "varkappa"   --> "\x1d6de"
  , "phi"        --> "\x1d6df"
  , "varrho"     --> "\x1d6e0"
  , "varpi"      --> "\x1d6e1"
  ]
  
mathItalicGreek :: [(String, String)]
mathItalicGreek =
  [ "Alpha"      --> "\x1d6e2"
  , "Beta"       --> "\x1d6e3"
  , "Gammma"     --> "\x1d6e4"
  , "Delta"      --> "\x1d6e5"
  , "Epsilon"    --> "\x1d6e6"
  , "Zeta"       --> "\x1d6e7"
  , "Eta"        --> "\x1d6e8"
  , "Theta"      --> "\x1d6e9"
  , "Iota"       --> "\x1d6ea"
  , "Kappa"      --> "\x1d6eb"
  , "Lambda"     --> "\x1d6ec"
  , "Mu"         --> "\x1d6ed"
  , "Nu"         --> "\x1d6ee"
  , "Xi"         --> "\x1d6ef"
  , "Omicron"    --> "\x1d6f0"
  , "Pi"         --> "\x1d6f1"
  , "Rho"        --> "\x1d6f2"
  , "varTheta"   --> "\x1d6f3"
  , "Sigma"      --> "\x1d6f4"
  , "Tau"        --> "\x1d6f5"
  , "Upsilon"    --> "\x1d6f6"
  , "Phi"        --> "\x1d6f7"
  , "Chi"        --> "\x1d6f8"
  , "Psi"        --> "\x1d6f9"
  , "Omega"      --> "\x1d6fa"
  , "nabla"      --> "\x1d6fb"

  , "alpha"      --> "\x1d6fc"
  , "beta"       --> "\x1d6fd"
  , "gamma"      --> "\x1d6fe"
  , "delta"      --> "\x1d6ff"
  , "varepsilon" --> "\x1d700"
  , "zeta"       --> "\x1d701"
  , "eta"        --> "\x1d702"
  , "theta"      --> "\x1d703"
  , "iota"       --> "\x1d704"
  , "kappa"      --> "\x1d705"
  , "lambda"     --> "\x1d706"
  , "mu"         --> "\x1d707"
  , "nu"         --> "\x1d708"
  , "xi"         --> "\x1d709"
  , "omicron"    --> "\x1d70a"
  , "pi"         --> "\x1d70b"
  , "rho"        --> "\x1d70c"
  , "varsigma"   --> "\x1d70d"
  , "sigma"      --> "\x1d70e"
  , "tau"        --> "\x1d70f"
  , "upsilon"    --> "\x1d710"
  , "varphi"     --> "\x1d711"
  , "chi"        --> "\x1d712"
  , "psi"        --> "\x1d713"
  , "omega"      --> "\x1d714"

  , "partial"    --> "\x1d715"
  , "epsilon"    --> "\x1d716"
  , "vartheta"   --> "\x1d717"
  , "varkappa"   --> "\x1d718"
  , "phi"        --> "\x1d719"
  , "varrho"     --> "\x1d71a"
  , "varpi"      --> "\x1d71b"
  ]
  
mathBoldItalicGreek :: [(String, String)]
mathBoldItalicGreek =
  [ "Alpha"      --> "\x1d71c"
  , "Beta"       --> "\x1d71d"
  , "Gammma"     --> "\x1d71e"
  , "Delta"      --> "\x1d71f"
  , "Epsilon"    --> "\x1d720"
  , "Zeta"       --> "\x1d721"
  , "Eta"        --> "\x1d722"
  , "Theta"      --> "\x1d723"
  , "Iota"       --> "\x1d724"
  , "Kappa"      --> "\x1d725"
  , "Lambda"     --> "\x1d726"
  , "Mu"         --> "\x1d727"
  , "Nu"         --> "\x1d728"
  , "Xi"         --> "\x1d729"
  , "Omicron"    --> "\x1d72a"
  , "Pi"         --> "\x1d72b"
  , "Rho"        --> "\x1d72c"
  , "varTheta"   --> "\x1d72d"
  , "Sigma"      --> "\x1d72e"
  , "Tau"        --> "\x1d72f"
  , "Upsilon"    --> "\x1d730"
  , "Phi"        --> "\x1d731"
  , "Chi"        --> "\x1d732"
  , "Psi"        --> "\x1d733"
  , "Omega"      --> "\x1d734"
  , "nabla"      --> "\x1d735"

  , "alpha"      --> "\x1d736"
  , "beta"       --> "\x1d737"
  , "gamma"      --> "\x1d738"
  , "delta"      --> "\x1d739"
  , "varepsilon" --> "\x1d73a"
  , "zeta"       --> "\x1d73b"
  , "eta"        --> "\x1d73c"
  , "theta"      --> "\x1d73d"
  , "iota"       --> "\x1d73e"
  , "kappa"      --> "\x1d73f"
  , "lambda"     --> "\x1d740"
  , "mu"         --> "\x1d741"
  , "nu"         --> "\x1d742"
  , "xi"         --> "\x1d743"
  , "omicron"    --> "\x1d744"
  , "pi"         --> "\x1d745"
  , "rho"        --> "\x1d746"
  , "varsigma"   --> "\x1d747"
  , "sigma"      --> "\x1d748"
  , "tau"        --> "\x1d749"
  , "upsilon"    --> "\x1d74a"
  , "varphi"     --> "\x1d74b"
  , "chi"        --> "\x1d74c"
  , "psi"        --> "\x1d74d"
  , "omega"      --> "\x1d74e"

  , "partial"    --> "\x1d74f"
  , "epsilon"    --> "\x1d750"
  , "vartheta"   --> "\x1d751"
  , "varkappa"   --> "\x1d752"
  , "phi"        --> "\x1d753"
  , "varrho"     --> "\x1d754"
  , "varpi"      --> "\x1d755"
  ]
  
mathSansSerifBoldGreek :: [(String, String)]
mathSansSerifBoldGreek =
  [ "Alpha"      --> "\x1d756"
  , "Beta"       --> "\x1d757"
  , "Gammma"     --> "\x1d758"
  , "Delta"      --> "\x1d759"
  , "Epsilon"    --> "\x1d75a"
  , "Zeta"       --> "\x1d75b"
  , "Eta"        --> "\x1d75c"
  , "Theta"      --> "\x1d75d"
  , "Iota"       --> "\x1d75e"
  , "Kappa"      --> "\x1d75f"
  , "Lambda"     --> "\x1d760"
  , "Mu"         --> "\x1d761"
  , "Nu"         --> "\x1d762"
  , "Xi"         --> "\x1d763"
  , "Omicron"    --> "\x1d764"
  , "Pi"         --> "\x1d765"
  , "Rho"        --> "\x1d766"
  , "varTheta"   --> "\x1d767"
  , "Sigma"      --> "\x1d768"
  , "Tau"        --> "\x1d769"
  , "Upsilon"    --> "\x1d76a"
  , "Phi"        --> "\x1d76b"
  , "Chi"        --> "\x1d76c"
  , "Psi"        --> "\x1d76d"
  , "Omega"      --> "\x1d76e"
  , "nabla"      --> "\x1d76f"

  , "alpha"      --> "\x1d770"
  , "beta"       --> "\x1d771"
  , "gamma"      --> "\x1d772"
  , "delta"      --> "\x1d773"
  , "varepsilon" --> "\x1d774"
  , "zeta"       --> "\x1d775"
  , "eta"        --> "\x1d776"
  , "theta"      --> "\x1d777"
  , "iota"       --> "\x1d778"
  , "kappa"      --> "\x1d779"
  , "lambda"     --> "\x1d77a"
  , "mu"         --> "\x1d77b"
  , "nu"         --> "\x1d77c"
  , "xi"         --> "\x1d77d"
  , "omicron"    --> "\x1d77e"
  , "pi"         --> "\x1d77f"
  , "rho"        --> "\x1d780"
  , "varsigma"   --> "\x1d781"
  , "sigma"      --> "\x1d782"
  , "tau"        --> "\x1d783"
  , "upsilon"    --> "\x1d784"
  , "varphi"     --> "\x1d785"
  , "chi"        --> "\x1d786"
  , "psi"        --> "\x1d787"
  , "omega"      --> "\x1d788"

  , "partial"    --> "\x1d789"
  , "epsilon"    --> "\x1d78a"
  , "vartheta"   --> "\x1d78b"
  , "varkappa"   --> "\x1d78c"
  , "phi"        --> "\x1d78d"
  , "varrho"     --> "\x1d78e"
  , "varpi"      --> "\x1d78f"
  ]

mathSansSerifBoldItalicGreek :: [(String, String)]
mathSansSerifBoldItalicGreek =
  [ "Alpha"      --> "\x1d790"
  , "Beta"       --> "\x1d791"
  , "Gammma"     --> "\x1d792"
  , "Delta"      --> "\x1d793"
  , "Epsilon"    --> "\x1d794"
  , "Zeta"       --> "\x1d795"
  , "Eta"        --> "\x1d796"
  , "Theta"      --> "\x1d797"
  , "Iota"       --> "\x1d798"
  , "Kappa"      --> "\x1d799"
  , "Lambda"     --> "\x1d79a"
  , "Mu"         --> "\x1d79b"
  , "Nu"         --> "\x1d79c"
  , "Xi"         --> "\x1d79d"
  , "Omicron"    --> "\x1d79e"
  , "Pi"         --> "\x1d79f"
  , "Rho"        --> "\x1d7a0"
  , "varTheta"   --> "\x1d7a1"
  , "Sigma"      --> "\x1d7a2"
  , "Tau"        --> "\x1d7a3"
  , "Upsilon"    --> "\x1d7a4"
  , "Phi"        --> "\x1d7a5"
  , "Chi"        --> "\x1d7a6"
  , "Psi"        --> "\x1d7a7"
  , "Omega"      --> "\x1d7a8"
  , "nabla"      --> "\x1d7a9"

  , "alpha"      --> "\x1d7aa"
  , "beta"       --> "\x1d7ab"
  , "gamma"      --> "\x1d7ac"
  , "delta"      --> "\x1d7ad"
  , "varepsilon" --> "\x1d7ae"
  , "zeta"       --> "\x1d7af"
  , "eta"        --> "\x1d7b0"
  , "theta"      --> "\x1d7b1"
  , "iota"       --> "\x1d7b2"
  , "kappa"      --> "\x1d7b3"
  , "lambda"     --> "\x1d7b4"
  , "mu"         --> "\x1d7b5"
  , "nu"         --> "\x1d7b6"
  , "xi"         --> "\x1d7b7"
  , "omicron"    --> "\x1d7b8"
  , "pi"         --> "\x1d7b9"
  , "rho"        --> "\x1d7ba"
  , "varsigma"   --> "\x1d7bb"
  , "sigma"      --> "\x1d7bc"
  , "tau"        --> "\x1d7bd"
  , "upsilon"    --> "\x1d7be"
  , "varphi"     --> "\x1d7bf"
  , "chi"        --> "\x1d7c0"
  , "psi"        --> "\x1d7c1"
  , "omega"      --> "\x1d7c2"

  , "partial"    --> "\x1d7c3"
  , "epsilon"    --> "\x1d7c4"
  , "vartheta"   --> "\x1d7c5"
  , "varkappa"   --> "\x1d7c6"
  , "phi"        --> "\x1d7c7"
  , "varrho"     --> "\x1d7c8"
  , "varpi"      --> "\x1d7c9"
  ]

mathBoldDigamma :: [(String, String)]
mathBoldDigamma =
  [ "Digamma" --> "\x1d7ca"
  , "digamma" --> "\x1d7cb"
  ]
  
mathBoldDigit :: [(String, String)]
mathBoldDigit =
  [ "0" --> "𝟎"
  , "1" --> "𝟏"
  , "2" --> "𝟐"
  , "3" --> "𝟑"
  , "4" --> "𝟒"
  , "5" --> "𝟓"
  , "6" --> "𝟔"
  , "7" --> "𝟕"
  , "8" --> "𝟖"
  , "9" --> "𝟗"
  ]

mathDoubleStruckDigit :: [(String, String)]
mathDoubleStruckDigit =
  [ "0" --> "𝟘"
  , "1" --> "𝟙"
  , "2" --> "𝟚"
  , "3" --> "𝟛"
  , "4" --> "𝟜"
  , "5" --> "𝟝"
  , "6" --> "𝟞"
  , "7" --> "𝟟"
  , "8" --> "𝟠"
  , "9" --> "𝟡"
  ]
 
mathSansSerifDigit :: [(String, String)]
mathSansSerifDigit =
  [ "0" --> "\x1d7e2"
  , "1" --> "\x1d7e3"
  , "2" --> "\x1d7e4"
  , "3" --> "\x1d7e5"
  , "4" --> "\x1d7e6"
  , "5" --> "\x1d7e7"
  , "6" --> "\x1d7e8"
  , "7" --> "\x1d7e9"
  , "8" --> "\x1d7ea"
  , "9" --> "\x1d7eb"
  ]
  
mathSansSerifBoldDigit :: [(String, String)]
mathSansSerifBoldDigit =
  [ "0" --> "\x1d7ec"
  , "1" --> "\x1d7ed"
  , "2" --> "\x1d7ee"
  , "3" --> "\x1d7ef"
  , "4" --> "\x1d7f0"
  , "5" --> "\x1d7f1"
  , "6" --> "\x1d7f2"
  , "7" --> "\x1d7f3"
  , "8" --> "\x1d7f4"
  , "9" --> "\x1d7f5"
  ]

mathMonospaceDigit :: [(String, String)]
mathMonospaceDigit =
  [ "0" --> "\x1d7f6"
  , "1" --> "\x1d7f7"
  , "2" --> "\x1d7f8"
  , "3" --> "\x1d7f9"
  , "4" --> "\x1d7fa"
  , "5" --> "\x1d7fb"
  , "6" --> "\x1d7fc"
  , "7" --> "\x1d7fd"
  , "8" --> "\x1d7fe"
  , "9" --> "\x1d7ff"
  ]
